### ISSUE TITLE
Crash when going back to List from Location picker, error, tap to retry, when Activity was killed

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#283]
This occurred to me during working on #278, worth checking back to it after the refactors.

Steps to reproduce:
1. Turn on "Don't keep Activities"
2. Modify code so that `EventListListLoaderFragment` error branch is executed
3. Start app, go to location picker, select a location
4. Tap on the error message to retry
Result: crash:
```
05-24 15:07:58.512 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.schedjoules.eventdiscovery.demo, PID: 27392
                                     java.lang.IllegalStateException: Activity has been destroyed
                                         at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1560)
                                         at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
                                         at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
                                         at com.schedjoules.eventdiscovery.framework.utils.fragment.Replace.doCommit(Replace.java:60)
                                         at com.schedjoules.eventdiscovery.framework.utils.fragment.Replace.commit(Replace.java:54)
                                         at com.schedjoules.eventdiscovery.framework.eventlist.EventListFragment.reloadList(EventListFragment.java:243)
                                         at com.schedjoules.eventdiscovery.framework.eventlist.EventListFragment.access$200(EventListFragment.java:74)
                                         at com.schedjoules.eventdiscovery.framework.eventlist.EventListFragment$3.onPigeonReturn(EventListFragment.java:158)
                                         at com.schedjoules.eventdiscovery.framework.eventlist.EventListFragment$3.onPigeonReturn(EventListFragment.java:154)
                                         at org.dmfs.android.microfragments.utils.BooleanDovecote$DovecotReceiver$1.run(BooleanDovecote.java:86)
                                         at org.dmfs.pigeonpost.localbroadcast.tools.MainThreadExecutor.execute(MainThreadExecutor.java:45)
                                         at org.dmfs.android.microfragments.utils.BooleanDovecote$DovecotReceiver.onReceive(BooleanDovecote.java:82)
                                         at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                         at android.support.v4.content.LocalBroadcastManager.sendBroadcastSync(LocalBroadcastManager.java:278)
                                         at org.dmfs.android.microfragments.utils.BooleanCage$2.send(BooleanCage.java:74)
                                         at com.schedjoules.eventdiscovery.framework.eventlist.EventListListErrorFragment$1.onClick(EventListListErrorFragment.java:69)
                                         at android.view.View.performClick(View.java:5204)
                                         at android.view.View$PerformClick.run(View.java:21153)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dmfs** [comment]
Hmm... maybe the Pigeon is still received by the Dovecote of the previous activity. In that case the Dovecote has not been destroyed properly.

**Comment by lemonboston** [comment]
Cannot reproduce it now on the header fragment branch. It could have been a not destroyed Dovecote in a certain stage of the refactors, I know at one point I noticed one of them was not disposed. So I consider this solved, moving to done with 1 story point.
