### ISSUE TITLE
SocketTimeoutException causes crash

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#352]
@lemonboston commented on [Mon Jul 24 2017](https://github.com/schedjoules/general-issues/issues/199)

I got this several times today while testing the new categories filtered discovery request, but from the stacktrace it has nothing to do with it.

@dmfs Can it be a bug in `http-client-essentials` that a timeout results in a `RuntimeException` propagated to the client?
(I haven't myself looked into it much yet)

```
07-24 13:55:04.758 E/AndroidRuntime: FATAL EXCEPTION: Thread-17470
                                     Process: com.schedjoules.eventdiscovery.demo, PID: 24605
                                     java.lang.RuntimeException: Can't get response code
                                         at org.dmfs.httpessentials.httpurlconnection.HttpUrlConnectionResponse.status(HttpUrlConnectionResponse.java:70)
                                         at com.schedjoules.client.eventsdiscovery.http.GetRequest.responseHandler(GetRequest.java:84)
                                         at org.dmfs.httpessentials.decoration.HeaderDecorated.responseHandler(HeaderDecorated.java:75)
                                         at org.dmfs.httpessentials.decoration.HeaderDecorated.responseHandler(HeaderDecorated.java:75)
                                         at com.schedjoules.client.http.GzipRequest.responseHandler(GzipRequest.java:116)
                                         at org.dmfs.httpessentials.decoration.HeaderDecorated.responseHandler(HeaderDecorated.java:75)
                                         at org.dmfs.httpessentials.decoration.HeaderDecorated.responseHandler(HeaderDecorated.java:75)
                                         at org.dmfs.httpessentials.decoration.HeaderDecorated.responseHandler(HeaderDecorated.java:75)
                                         at org.dmfs.httpessentials.httpurlconnection.PlainHttpUrlConnectionExecutor.execute(PlainHttpUrlConnectionExecutor.java:81)
                                         at org.dmfs.httpessentials.httpurlconnection.utils.executors.BottomBranded.execute(BottomBranded.java:56)
                                         at org.dmfs.httpessentials.httpurlconnection.utils.executors.BottomBranded.execute(BottomBranded.java:56)
                                         at org.dmfs.httpessentials.httpurlconnection.HttpUrlConnectionExecutor.execute(HttpUrlConnectionExecutor.java:68)
                                         at org.dmfs.httpessentials.executors.retrying.Retrying.retryingExecute(Retrying.java:68)
                                         at org.dmfs.httpessentials.executors.retrying.Retrying.execute(Retrying.java:60)
                                         at org.dmfs.httpessentials.executors.useragent.Branded.execute(Branded.java:55)
                                         at com.schedjoules.eventdiscovery.framework.http.RequestUriAndTimeLogging$LoggingExecutor.execute(RequestUriAndTimeLogging.java:85)
                                         at com.schedjoules.eventdiscovery.framework.http.RequestUriAndTimeLogging.execute(RequestUriAndTimeLogging.java:56)
                                         at com.schedjoules.client.http.Gzipping.execute(Gzipping.java:52)
                                         at org.dmfs.httpessentials.executors.useragent.Branded.execute(Branded.java:55)
                                         at org.dmfs.httpessentials.executors.urlrewriting.UrlRewriting.execute(UrlRewriting.java:60)
                                         at com.schedjoules.client.SchedJoulesApi.queryResult(SchedJoulesApi.java:67)
                                         at com.schedjoules.client.eventsdiscovery.queries.SimpleEventsDiscovery.queryResult(SimpleEventsDiscovery.java:162)
                                         at com.schedjoules.client.eventsdiscovery.queries.SimpleEventsDiscovery.queryResult(SimpleEventsDiscovery.java:53)
                                         at com.schedjoules.eventdiscovery.framework.eventlist.controller.InitialEventsDiscovery.queryResult(InitialEventsDiscovery.java:129)
                                         at com.schedjoules.eventdiscovery.framework.eventlist.controller.InitialEventsDiscovery.queryResult(InitialEventsDiscovery.java:62)
                                         at com.schedjoules.eventdiscovery.service.AbstractApiService$ApiServiceBinder.apiResponse(AbstractApiService.java:97)
                                         at com.schedjoules.eventdiscovery.framework.eventlist.EventListListLoaderFragment$1.run(EventListListLoaderFragment.java:104)
                                         at java.lang.Thread.run(Thread.java:818)
                                      Caused by: java.net.SocketTimeoutException: timeout
                                         at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
                                         at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                         at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                         at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                         at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                         at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                         at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                         at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                         at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
                                         at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
                                         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
                                         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                     	at 

```

---

@lemonboston commented on [Mon Jul 24 2017](https://github.com/schedjoules/general-issues/issues/199#issuecomment-317401361)

It may happen when firing discovery request right after each other (tapping on the filter) and replacing fragments.

---

@dmfs commented on [Mon Jul 24 2017](https://github.com/schedjoules/general-issues/issues/199#issuecomment-317407288)

It's a known issue in http-client-essentials. I've already addressed this in some experimental branch. Please raise an issue in http-client-essentials.

---

@dmfs commented on [Mon Jul 24 2017](https://github.com/schedjoules/general-issues/issues/199#issuecomment-317407535)

Nevertheless we need to check why the server times out. That might be a server issue.

---

@lemonboston commented on [Tue Jul 25 2017](https://github.com/schedjoules/general-issues/issues/199#issuecomment-317628783)

I see you have created the ticket: https://github.com/dmfs/http-client-essentials-suite/issues/52

**Comment by lemonboston** [comment]
The ticket in `http-client-essentials` is approved, once that is merged and new tag released, we can update the SDK to use that.

**Comment by dmfs** [comment]
`http-client-essentials-suite` 0.12.1 has been released.
