### ISSUE TITLE
Unclear crash upon discovery launch caused by missing categories cache

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#373]
This happened twice but only during development when relaunching the app frequently from Android Studio, so it's not clear if this can be an actual live-bug or not.

```
07-27 15:05:41.366 D/EventDiscovery-Request: (3) Response time: 877 ms
07-27 15:05:41.580 D/AndroidRuntime: Shutting down VM
07-27 15:05:41.581 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.schedjoules.eventdiscovery.demo, PID: 23321
                                     android.view.InflateException: Binary XML file line #31: Cannot create an instance of class com.schedjoules.eventdiscovery.framework.common.CategoriesCache
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                         at com.schedjoules.eventdiscovery.framework.filter.FilterFragment.onCreateView(FilterFragment.java:65)
                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                         at android.support.v4.app.Fragment.performStart(Fragment.java:2211)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                         at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763)
                                         at org.dmfs.android.microfragments.HostFragment.executeTransition(HostFragment.java:209)
                                         at org.dmfs.android.microfragments.HostFragment.onPigeonReturn(HostFragment.java:186)
                                         at org.dmfs.android.microfragments.HostFragment.onPigeonReturn(HostFragment.java:50)
                                         at org.dmfs.pigeonpost.localbroadcast.ParcelableDovecote$DovecotReceiver$1.run(ParcelableDovecote.java:103)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                      Caused by: java.lang.RuntimeException: Cannot create an instance of class com.schedjoules.eventdiscovery.framework.common.CategoriesCache
                                         at android.arch.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:145)
                                         at android.arch.lifecycle.ViewModelProviders$DefaultFactory.create(ViewModelProviders.java:143)
                                         at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:128)
                                         at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:96)
                                         at com.schedjoules.eventdiscovery.framework.common.CategoriesCache.<init>(CategoriesCache.java:0)
                                         at com.schedjoules.eventdiscovery.framework.filter.views.EventFilterView.onFinishInflate(EventFilterView.java:103)
                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:844)
                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                         at com.schedjoules.eventdiscovery.framework.filter.FilterFragment.onCreateView(FilterFragment.java:65) 
                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189) 
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757) 
                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355) 
                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146) 
                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098) 
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008) 
                                         at android.support.v4.app.Fragment.performStart(Fragment.java:2211) 
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340) 
                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757) 
                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355) 
                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146) 
                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098) 
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008) 
                                         at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763) 
                                         at org.dmfs.android.microfragments.HostFragment.executeTransition(HostFragment.java:209) 
                                         at org.dmfs.android.microfragments.HostFragment.onPigeonReturn(HostFragment.java:186) 
                                         at org.dmfs.android.microfragments.HostFragment.onPigeonReturn(HostFragment.java:50) 
                                         at org.dmfs.pigeonpost.localbroadcast.ParcelableDovecote$DovecotReceiver$1.run(ParcelableDovecote.java:103) 
                                         at android.os.Handler.handleCallback(Handler.java:739) 
                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                         at android.os.Looper.loop(Looper.java:148) 
                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                         at java.lang.reflect.Method.invoke(Native Method) 
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                      Caused by: java.lang.InstantiationException: java.lang.Class<com.schedjoules.eventdiscovery.framework.common.CategoriesCache> has no zero argument constructor
                                     	at java.lang.Class.newInstance(Nati
07-27 15:06:10.449 D/EventDiscovery-Request: (4) POST https://api.schedjoules.com/insights?u=b3e9f91c-2897-44d5-8ddb-770e4cfa277e
07-27 15:06:10.745 D/EventDiscovery-Request: (4) Response time: 296 ms
```

**Comment by lemonboston** [comment]
Just had another from this. Fresh app start (hadn't been running in the background) from Android Studio from branch `categories/341-filter-ui`. 

```
08-01 14:51:35.868 D/AndroidRuntime: Shutting down VM
08-01 14:51:35.875 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.schedjoules.eventdiscovery.demo, PID: 32343
                                     android.view.InflateException: Binary XML file line #33: Cannot create an instance of class com.schedjoules.eventdiscovery.framework.common.CategoriesCache
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                         at com.schedjoules.eventdiscovery.framework.filter.FilterFragment.onCreateView(FilterFragment.java:65)
                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                         at android.support.v4.app.Fragment.performStart(Fragment.java:2211)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                         at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763)
                                         at org.dmfs.android.microfragments.HostFragment.executeTransition(HostFragment.java:209)
                                         at org.dmfs.android.microfragments.HostFragment.onPigeonReturn(HostFragment.java:186)
                                         at org.dmfs.android.microfragments.HostFragment.onPigeonReturn(HostFragment.java:50)
                                         at org.dmfs.pigeonpost.localbroadcast.ParcelableDovecote$DovecotReceiver$1.run(ParcelableDovecote.java:103)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                      Caused by: java.lang.RuntimeException: Cannot create an instance of class com.schedjoules.eventdiscovery.framework.common.CategoriesCache
                                         at android.arch.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:145)
                                         at android.arch.lifecycle.ViewModelProviders$DefaultFactory.create(ViewModelProviders.java:143)
                                         at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:128)
                                         at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:96)
                                         at com.schedjoules.eventdiscovery.framework.common.CategoriesCache.<init>(CategoriesCache.java:0)
                                         at com.schedjoules.eventdiscovery.framework.filter.views.EventFilterView.onFinishInflate(EventFilterView.java:107)
                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:844)
                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                         at com.schedjoules.eventdiscovery.framework.filter.FilterFragment.onCreateView(FilterFragment.java:65) 
                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189) 
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757) 
                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355) 
                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146) 
                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098) 
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008) 
                                         at android.support.v4.app.Fragment.performStart(Fragment.java:2211) 
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340) 
                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757) 
                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355) 
                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146) 
                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098) 
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008) 
                                         at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763) 
                                         at org.dmfs.android.microfragments.HostFragment.executeTransition(HostFragment.java:209) 
                                         at org.dmfs.android.microfragments.HostFragment.onPigeonReturn(HostFragment.java:186) 
                                         at org.dmfs.android.microfragments.HostFragment.onPigeonReturn(HostFragment.java:50) 
                                         at org.dmfs.pigeonpost.localbroadcast.ParcelableDovecote$DovecotReceiver$1.run(ParcelableDovecote.java:103) 
                                         at android.os.Handler.handleCallback(Handler.java:739) 
                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                         at android.os.Looper.loop(Looper.java:148) 
                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                         at java.lang.reflect.Method.invoke(Native Method) 
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                      Caused by: java.lang.InstantiationException: java.lang.Class<com.schedjoules.eventdiscovery.framework.common.CategoriesCache> has no zero argument constructor
                                     	at java.lang.Class.newInstance(Nati
08-01 14:52:04.732 D/EventDiscovery-Request: (4) POST https://api.schedjoules.com/insights?u=8bc53435-66f2-4569-8767-5ebb94e60b05
```

**Comment by dmfs** [comment]
We should look into that. I might happen for partner installs as well.

**Comment by dmfs** [comment]
If there is a chance that `CategoriesCache` is instantiated automatically we need to make sure it doesn't break the SDK. Could this be a race condition?

**Comment by lemonboston** [comment]
What I can think of as possible causes currently:

A) Splash loader MF somehow proceeds before categories load finished
(As I recall it may have happened pretty fast after I tapped on the discovery button, so that would point to this, but I am not sure.)

B) There is some async stuff involved in setting up the ViewModel and it doesn't finish until the filter asks for the instance

None of it seem likely, but I am checking.

What do you mean about the race condition in which part?

**Comment by dmfs** [comment]
@lemonboston is this supposed to be fixed by one of the recent commits?

**Comment by lemonboston** [comment]
Since this cannot be reproduced reliably we can't be sure, but yes, if the problem was the usage and way of usage of ViewModel for the categories cache - which I think is the most likely reason - then https://github.com/schedjoules/android-event-discovery-sdk/pull/394 supposed to have fixed this.

So I think this can be closed and we can reopen or open new one if we encounter it again.
(Also worth noting again that this was observed during development only, it wasn't a reported bug.)

**Comment by dmfs** [comment]
Ok, I closing it.
