### ISSUE TITLE
App crash when home is pressed while details screen is loading

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#66]
Doesn't happen always, but the app can crash if the home button is pressed while the details screen is loading.

Stacktrace:
```
12-30 13:16:47.454 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.schedjoules.eventdiscovery.demo, PID: 31014
                                     java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                         at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1538)
                                         at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1556)
                                         at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
                                         at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
                                         at com.schedjoules.eventdiscovery.eventdetails.transitions.ForwardFadeOperation.apply(ForwardFadeOperation.java:79)
                                         at org.dmfs.android.dumbledore.WizardHost$1$1.run(WizardHost.java:161)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dmfs** [comment]
fixed by #60
